import { storage } from "./storage";

const svOberglanPlayers = [
  // Herren Kader
  {
    firstName: "Lukas",
    lastName: "Brandstetter",
    jerseyNumber: 1,
    position: "Tor",
    birthDate: "1990-03-15",
    nationality: "Österreich",
    height: 185,
    weight: 80,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4501",
    email: "l.brandstetter@svoberglan.at"
  },
  {
    firstName: "Thomas",
    lastName: "Huber",
    jerseyNumber: 3,
    position: "Verteidigung",
    birthDate: "1992-08-22",
    nationality: "Österreich",
    height: 182,
    weight: 78,
    preferredFoot: "left",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4503",
    email: "t.huber@svoberglan.at"
  },
  {
    firstName: "Martin",
    lastName: "Schwarz",
    jerseyNumber: 5,
    position: "Verteidigung",
    birthDate: "1989-11-10",
    nationality: "Österreich",
    height: 180,
    weight: 75,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4505",
    email: "m.schwarz@svoberglan.at"
  },
  {
    firstName: "David",
    lastName: "Moser",
    jerseyNumber: 7,
    position: "Mittelfeld",
    birthDate: "1993-05-18",
    nationality: "Österreich",
    height: 175,
    weight: 72,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4507",
    email: "d.moser@svoberglan.at"
  },
  {
    firstName: "Alexander",
    lastName: "Weber",
    jerseyNumber: 8,
    position: "Mittelfeld",
    birthDate: "1991-12-03",
    nationality: "Österreich",
    height: 178,
    weight: 73,
    preferredFoot: "left",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4508",
    email: "a.weber@svoberglan.at"
  },
  {
    firstName: "Michael",
    lastName: "Steiner",
    jerseyNumber: 9,
    position: "Sturm",
    birthDate: "1988-07-25",
    nationality: "Österreich",
    height: 183,
    weight: 79,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4509",
    email: "m.steiner@svoberglan.at"
  },
  {
    firstName: "Patrick",
    lastName: "Gruber",
    jerseyNumber: 10,
    position: "Mittelfeld",
    birthDate: "1994-04-12",
    nationality: "Österreich",
    height: 176,
    weight: 71,
    preferredFoot: "both",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4510",
    email: "p.gruber@svoberglan.at"
  },
  {
    firstName: "Stefan",
    lastName: "Bauer",
    jerseyNumber: 11,
    position: "Sturm",
    birthDate: "1990-09-07",
    nationality: "Österreich",
    height: 181,
    weight: 76,
    preferredFoot: "left",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4511",
    email: "s.bauer@svoberglan.at"
  },
  {
    firstName: "Andreas",
    lastName: "Fischer",
    jerseyNumber: 4,
    position: "Verteidigung",
    birthDate: "1987-01-28",
    nationality: "Österreich",
    height: 179,
    weight: 74,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4504",
    email: "a.fischer@svoberglan.at"
  },
  {
    firstName: "Christian",
    lastName: "Hofer",
    jerseyNumber: 6,
    position: "Mittelfeld",
    birthDate: "1995-06-14",
    nationality: "Österreich",
    height: 177,
    weight: 70,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4506",
    email: "c.hofer@svoberglan.at"
  },
  {
    firstName: "Daniel",
    lastName: "Pichler",
    jerseyNumber: 12,
    position: "Tor",
    birthDate: "1996-02-20",
    nationality: "Österreich",
    height: 188,
    weight: 82,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4512",
    email: "d.pichler@svoberglan.at"
  },
  // Reserve Bank
  {
    firstName: "Florian",
    lastName: "Mair",
    jerseyNumber: 13,
    position: "Verteidigung",
    birthDate: "1997-10-11",
    nationality: "Österreich",
    height: 174,
    weight: 69,
    preferredFoot: "left",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4513",
    email: "f.mair@svoberglan.at"
  },
  {
    firstName: "Markus",
    lastName: "Reiter",
    jerseyNumber: 14,
    position: "Mittelfeld",
    birthDate: "1992-12-08",
    nationality: "Österreich",
    height: 173,
    weight: 68,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4514",
    email: "m.reiter@svoberglan.at"
  },
  {
    firstName: "Johannes",
    lastName: "Lang",
    jerseyNumber: 15,
    position: "Sturm",
    birthDate: "1999-03-30",
    nationality: "Österreich",
    height: 184,
    weight: 77,
    preferredFoot: "right",
    status: "active" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4515",
    email: "j.lang@svoberglan.at"
  },
  // Verletzter Spieler
  {
    firstName: "Robert",
    lastName: "Auer",
    jerseyNumber: 16,
    position: "Mittelfeld",
    birthDate: "1990-05-22",
    nationality: "Österreich",
    height: 175,
    weight: 71,
    preferredFoot: "left",
    status: "injured" as const,
    contractStart: "2024-07-01",
    contractEnd: "2025-06-30",
    profileImageUrl: "",
    phone: "+43 664 123 4516",
    email: "r.auer@svoberglan.at",
    notes: "Kreuzbandriss - Rückkehr voraussichtlich März 2025"
  }
];

export async function seedPlayers(clubId: number) {
  console.log("Seeding players for SV Oberglan 1975...");
  
  for (const playerData of svOberglanPlayers) {
    try {
      await storage.createPlayer({
        ...playerData,
        clubId,
      });
      console.log(`Created player: ${playerData.firstName} ${playerData.lastName}`);
    } catch (error) {
      console.error(`Error creating player ${playerData.firstName} ${playerData.lastName}:`, error);
    }
  }
  
  console.log("Player seeding completed!");
}